name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/timoschwarzbach/fis-manage:latest
            ghcr.io/timoschwarzbach/fis-manage:${{ github.sha }}
