name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/timoschwarzbach/fis-manage:latest
            ghcr.io/timoschwarzbach/fis-manage:${{ github.sha }}
          secret-envs: |
            MINIO_ENDPOINT=http://example.com
            MINIO_SSL=true
            MINIO_PORT=443
            MINIO_ACCESS_KEY=minio
            MINIO_SECRET_KEY=miniosecret
            MINIO_BUCKET_NAME=fis
            DATABASE_URL="postgresql://postgres:password@localhost:5432/fis-manage"
            TAGESSCHAU_SERVICE_URL="https://tagesschauscraper/tagesschau"
